### ISSUE TITLE
Add the DF description to Riot

### ISSUE THREAD

**Issue by TurboUrbo** [decentfund/General#2]
🙂 Decent.Fund mission is to contribute to the mass adoption of the decentralized solutions, making the concepts of the new crypto economy closer to unchain world.
 According to the mission Decent.Fund focuses on the following types of activities which are divided between domains:
🦄 DEV domain (UI/UX design, programming, digital marketing)
✏️ EDU domain (research, articles, infographics, meetups, hackathons, social activity)
📈  FUND management domain (smart investment, crypto asset management)
💛 GOV domain (strategy)

In Riot we have different channels related to topics. Choose what you like. Feel free to communicate!  Work, learn and have fun! 💪🏿

**Comment by igorline** [comment]
@TurboUrbo, can you, please also post here channels we are openning to public?

Btw, I guess we can use emojis in text to make it fancy :)

**Comment by TurboUrbo** [comment]
😉 no prob
Introduction
KYODO
Random
Education
Medium
Twitter
Fund
Muchoxxx
FOAM
ExplainmeLikeIam5
Makerfolio
Memes Factory 

Correct me if i'm missing smth

**Comment by igorline** [comment]
@TurboUrbo, @alinaloseva we are missing icon for next channels: 
Introduction
Memes Factory

What is Fund channel? Should we open it?

**Comment by igorline** [comment]
Here you can view our public community page
https://riot.im/app/#/group/+dao:matrix.decent.fund

I have opened next channel to general audience
![image](https://user-images.githubusercontent.com/1465430/47814020-eab84d00-dd4c-11e8-83a3-fb6d4e6dd589.png)

**Comment by igorline** [comment]
I'd reckon to keep mucho private btw!

**Comment by igorline** [comment]
Added subdomain for easier way to join us
http://riot.decent.fund/

**Comment by TurboUrbo** [comment]
> I'd reckon to keep mucho private btw!

agree

**Comment by igorline** [comment]
@TurboUrbo, if everything is right, please, close the issue and maybe we can start slowly to share it!

**Comment by TurboUrbo** [comment]
OK

**Comment by TurboUrbo** [comment]
> @TurboUrbo, @alinaloseva we are missing icon for next channels:
> Introduction
> Memes Factory
> 
> What is Fund channel? Should we open it?

Kyodo Github

**Comment by TurboUrbo** [comment]
> @TurboUrbo, @alinaloseva we are missing icon for next channels:
> Introduction
> Memes Factory
> 
> What is Fund channel? Should we open it?

Done
Also @alinaloseva made the icon for Kyodo Github
